version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_tr3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: dualspirit

  mysql:
    image: mysql:8.0
    container_name: mysql_tr3
    restart: always
    ports:
      - "3307:3308"  # Cambiado a 3307 para evitar conflictos
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dualspirit

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_tr3
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_tr3
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev

  adminer:
    image: adminer:latest
    container_name: adminer_tr3
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      ADMINER_DEFAULT_SERVER: mysql_tr3  # Conectar a MySQL por defecto

volumes:
  mongodb_data:
  mysql_data: