version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_tr3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: dualspirit

  mysql:
    image: mysql:8.0
    container_name: mysql_tr3
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dualspirit

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_tr3
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./backend:/app/backend
    command: ["node", "app.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_tr3
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run serve

  adminer:
    image: adminer:latest
    container_name: adminer_tr3
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql_tr3

volumes:
  mongodb_data: {}
  mysql_data: {}