version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_tr3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: dualspirit

  app:
    build: .
    container_name: node_app_tr3
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongodb_data: